-- Curious: Initial database schema
-- Only interpreted understanding and connections live in Supabase.
-- Raw conversations, recordings, and photos stay in on-device IndexedDB.

-- User profiles (extends Supabase auth.users)
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL DEFAULT '',
  voice_style JSONB NOT NULL DEFAULT '{"tone":"warm-neutral","directness":0.5,"metaphor_affinity":0.5}',
  total_conversations INT NOT NULL DEFAULT 0,
  last_conversation_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', ''));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- The agent's interpreted understanding, stored as individual facets
CREATE TABLE understanding_facets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  domain TEXT NOT NULL CHECK (domain IN (
    'identity', 'values', 'relationships', 'purpose',
    'experiences', 'patterns', 'aspirations', 'struggles', 'joys', 'worldview'
  )),
  content TEXT NOT NULL,
  confidence REAL NOT NULL DEFAULT 0.5,
  depth INT NOT NULL DEFAULT 1,
  source_turn_ids TEXT[] DEFAULT '{}',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_facets_user_active ON understanding_facets(user_id) WHERE is_active = true;

-- Session metadata (NOT raw transcripts)
CREATE TABLE conversation_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  session_summary TEXT,
  themes TEXT[] DEFAULT '{}',
  agent_notes TEXT,
  message_count INT NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  ended_at TIMESTAMPTZ
);

-- Reflections generated by the agent
CREATE TABLE reflections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  domains TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Agent gifts
CREATE TABLE agent_gifts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gifter_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  recipient_email TEXT NOT NULL,
  recipient_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  briefing TEXT NOT NULL,
  relationship_label TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  invite_code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  claimed_at TIMESTAMPTZ
);

-- Connections (created when a gift is accepted)
CREATE TABLE connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gift_id UUID REFERENCES agent_gifts(id) ON DELETE CASCADE,
  user_a_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  user_b_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  tier_a_to_b TEXT NOT NULL DEFAULT 'personal' CHECK (tier_a_to_b IN ('surface', 'personal', 'deep')),
  tier_b_to_a TEXT NOT NULL DEFAULT 'surface' CHECK (tier_b_to_a IN ('surface', 'personal', 'deep')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_a_id, user_b_id)
);

-- Agent-to-agent query log
CREATE TABLE agent_queries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  connection_id UUID REFERENCES connections(id) ON DELETE CASCADE NOT NULL,
  query_text TEXT NOT NULL,
  response_text TEXT,
  tier TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE understanding_facets ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reflections ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_gifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_queries ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "own_profile" ON profiles FOR ALL USING (auth.uid() = id);
CREATE POLICY "own_facets" ON understanding_facets FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "own_sessions" ON conversation_sessions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "own_reflections" ON reflections FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "own_gifts" ON agent_gifts FOR ALL USING (auth.uid() = gifter_id);
CREATE POLICY "see_connections" ON connections FOR SELECT
  USING (auth.uid() = user_a_id OR auth.uid() = user_b_id);
CREATE POLICY "update_own_tier" ON connections FOR UPDATE
  USING (auth.uid() = user_a_id OR auth.uid() = user_b_id);
CREATE POLICY "see_queries" ON agent_queries FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM connections c WHERE c.id = connection_id
    AND (c.user_a_id = auth.uid() OR c.user_b_id = auth.uid())
  ));
